# https://support.google.com/mail/answer/7126229?visit_id=1-636695558676840231-1894077264&rd=2#cantsignin
spring:
  mail:
    host: smtp.gmail.com #发送邮件服务器
    username: xxx@gmail.com #QQ邮箱
    password: xxx #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: xxx@gmail.com #与上面的username保持一致

#---
#spring:
#  profiles: qq #腾讯QQ
#  mail:
#    host: smtp.qq.com #发送邮件服务器
#    username: xx@qq.com #QQ邮箱
#    password: xxxxxxxxxxx #客户端授权码
#    protocol: smtp #发送邮件协议
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.port: 465 #端口号465或587
#    properties.mail.display.sendmail: Javen #可以任意
#    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    properties.mail.smtp.ssl.enable: true
#    default-encoding: utf-8
#    from: xx@qq.com #与上面的username保持一致
#
#
#---
#spring:
#  profiles: wy #网易
#  mail:
#    host: smtp.qq.com #发送邮件服务器
#    username: xx@qq.com #QQ邮箱
#    password: xxxxxxxxxxx #客户端授权码
#    protocol: smtp #发送邮件协议
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.port: 465 #端口号465或587
#    properties.mail.display.sendmail: Javen #可以任意
#    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    properties.mail.smtp.ssl.enable: true
#    default-encoding: utf-8
#    from: xx@qq.com #与上面的username保持一致


